use_frameworks!
platform :ios, "9.0"
pod "SocketRocket"

target 'CabPrj2’ do
  pod 'Starscream', '~> 1.0'
end



source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
